# Generated by Django 2.1.3 on 2019-02-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='notesitem',
            name='note',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='note_item', to='notes.Note'),
        ),
    ]
