# Generated by Django 2.1.5 on 2019-02-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120,
                                          verbose_name='Название')),
                ('weight', models.FloatField(blank=True,
                                             null=True, verbose_name='Количество в граммах')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120,
                                          verbose_name='Название')),
                ('weight', models.FloatField(blank=True,
                                             null=True, verbose_name='Количество в граммах')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=120, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='order_dish', to='coocking_book.Dish')),
                ('ingredients', models.ManyToManyField(
                    related_name='orders', to='coocking_book.IngredientInOrder')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(
                related_name='dishes', to='coocking_book.Ingredient'),
        ),
    ]
