# Generated by Django 2.1.5 on 2019-02-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
