# Generated by Django 2.1.3 on 2019-02-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0002_ingredient_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_active',
        ),
    ]
