# Generated by Django 2.1.3 on 2019-02-14 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0004_auto_20190213_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
